add-controllers
ddddubbbb/java-shareit pull request #1
Opened 2023-11-21 20:04 UTC by ddddubbbb

2023-11-22 07:26 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +    private static class ErrorResponse {
Лучше сделать публичным, потому как не логично, публичный метод отдает приватный класс

2023-11-22 07:29 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +}
и еще добавь
	@ExceptionHandler
	@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(final Throwable e) {
		log.info("500 {}", e.getMessage(), e);
		return new ErrorResponse(e.getMessage());
	}
чтобы остальные необработанные исключения тоже отловились

2023-11-22 07:31 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    public Map<Long, Item> items;
А что так радикально, public)?

2023-11-22 07:39 UTC, VadimZharkov requested changes
Посмотри, что можно улучшить

2023-11-23 10:11 UTC, ddddubbbb commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    public Map<Long, Item> items;
исправил на private

2023-11-23 10:12 UTC, ddddubbbb commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +}
Добавил

2023-11-23 10:12 UTC, ddddubbbb commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +    private static class ErrorResponse {
ок

2023-11-24 06:28 UTC, VadimZharkov approved these changes

2023-12-04 13:53 UTC, merged