Add docker
ddddubbbb/java-shareit pull request #5
Opened 2024-01-18 14:56 UTC by ddddubbbb

2024-01-20 06:29 UTC, ddddubbbb commented
не могу понять почему сервер не запускается

2024-01-20 13:47 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +import org.springframework.validation.annotation.Validated;
В сервере зависимостей от валидации уже быть не должно, все проверится в gateway

2024-01-20 13:50 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/exception/handler/ErrorHandler.java
> +    private static class ErrorResponse {
Лучше сделать public, т.к. выше публичные методы отдают приватный класс, диссонанс.
В gateway тоже поправь.

2024-01-20 13:52 UTC, VadimZharkov requested changes
Можно улучшить

2024-01-21 17:13 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        item.stream().map(this::updateBookings).forEach(i -> {
Очень не оптимально реализовано.
Два раза проход в цикле с доп. запросами к БД. в map(updateBookings) и в forEach
Нужно постараться переделать.

2024-01-21 17:15 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            CommentMapper.toDtoList(commentRepository.findAllByItemIdOrderByCreated(i.getId()));
CommentMapper.toDtoList возвращает список, который не используется, для чего тогда?

2024-01-22 07:41 UTC, VadimZharkov approved these changes

2024-01-22 09:13 UTC, merged